
---
- name: Install Apache and Upload my Web Page 
  hosts: test
  become: yes


  vars:
    source_file: ./MyWebSite/index.html
    distin_file: /var/www/html


  tasks:
  - name: 1/3 -Install Apache Web Server
    yum: name=apache2 state=latest

  - name: 2/3 -Copy my Page from local in to Server's
    copy: src={{ source_file }} dest={{ distin_file }} mode=0555
    notify: Restart Apache
    become: yes

  - name: 3/3 -Start WebServer and Enable on boot
    service: name=apache2 state=started


  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
